name: ci
on:
  push:
    branches:
      - '**'
      
jobs:
  check:
    name: Update Open Source Layers Reference
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Update Open Source Layers Reference
        run: |
          export reviewer1=UmairAsghar-max

          git config --global user.name "${{ github.event.head_commit.author.name }}"
          git config --global user.email "${{ github.event.head_commit.author.email }}"

          git checkout -b feature/layers-ref-update
          git submodule update --init --recursive

          git submodule foreach '
              latest_release=$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1)
              if [ -n "$latest_release" ]; then
                  if [ "$(git rev-parse HEAD)" != "$(git rev-parse $latest_release)" ]; then
                  echo "Latest Release: $latest_release"
                  echo "Latest Release Commit SHA: $(git rev-parse $latest_release)"
                  git checkout "$latest_release"
                  fi
              fi
              '
          if [ -n "$(git status --porcelain)" ]; then
            if [ -n "$(gh pr list --head feature/layers-ref-update)" ]; then
              gh pr list --head feature/layers-ref-update
              echo "Pull Request already exists!"
              exit 0
            else
              git commit -am "Update open source layers reference" -m "Body" -m "[Neext-2121]"
              git push origin feature/layers-ref-update
              gh pr create --title "Update open source layers reference" --body "Update open source layers reference" --base ${GITHUB_REF#refs/heads/} --reviewer $reviewer1
            fi
          else
            echo "Everything already uptodate, Nothing to Commit"
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
